version: "3"

services:
  app:
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

networks:
  overlay:
