version: "3.7"

services:
  mongo:
    restart: always
    image: mongo
    volumes:
      - node-react-starter-db:/data/db
    ports:
      - "27017:27017"
    networks:
      - node-react-starter-network

  app:
    restart: always
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    networks:
      - node-react-starter-network

volumes:
  node-react-starter-db:
    name: node-react-starter-db

networks:
  node-react-starter-network:
    name: node-react-starter-network
